env:
  browser: true
  es2021: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
  - 'plugin:@typescript-eslint/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  # 関数の複雑さを 10 以下にする
  complexity: ['error', 10]
  # React のプロパティの型チェックを省略する (TypeScript でチェックされるため)
  react/prop-types: off
  # インターフェースの先頭文字を "I" にする
  '@typescript-eslint/naming-convention':
    - error
    - prefixWithI: 'always'
  prettier/prettier:
    - error
